sources:
  - name: redshift_raw
    database: redshift_dev  
    schema: jaffle_shop
    tables:
      - name: orders

  - name: snowflake_raw
    database: raw
    schema: jaffle_shop
    tables:
      - name: orders