sources:
  - name: redshift_raw
    database: "{{env_var('DBT_DATABASE')}}"  
    schema: jaffle_shop
    tables:
      - name: orders

  - name: snowflake_raw
    database: raw
    schema: jaffle_shop
    tables:
      - name: orders
